onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_mips_processor/clk
add wave -noupdate /tb_mips_processor/reset
add wave -noupdate /tb_mips_processor/alu_output
add wave -noupdate /tb_mips_processor/write_data
add wave -noupdate /tb_mips_processor/uut/clk
add wave -noupdate /tb_mips_processor/uut/reset
add wave -noupdate /tb_mips_processor/uut/alu_output
add wave -noupdate /tb_mips_processor/uut/write_data
add wave -noupdate /tb_mips_processor/uut/RegDst_s
add wave -noupdate /tb_mips_processor/uut/ALUSrc_s
add wave -noupdate /tb_mips_processor/uut/MemtoReg_s
add wave -noupdate /tb_mips_processor/uut/RegWrite_s
add wave -noupdate /tb_mips_processor/uut/zero_flag
add wave -noupdate /tb_mips_processor/uut/PCSrc
add wave -noupdate /tb_mips_processor/uut/MemRead_s
add wave -noupdate /tb_mips_processor/uut/MemWrite_s
add wave -noupdate /tb_mips_processor/uut/Branch_s
add wave -noupdate /tb_mips_processor/uut/Jump_s
add wave -noupdate /tb_mips_processor/uut/ALUOp_s
add wave -noupdate /tb_mips_processor/uut/branchtype_s
add wave -noupdate /tb_mips_processor/uut/instruction
add wave -noupdate /tb_mips_processor/uut/alu_out
add wave -noupdate /tb_mips_processor/uut/mem_read_data
add wave -noupdate /tb_mips_processor/uut/reg_write_data
add wave -noupdate /tb_mips_processor/uut/PC
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/instr
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/aluoperation
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/zero
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/nflag
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/regwrite
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RegDst
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/MemtoReg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/AluSrc
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/read_data
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/Jump
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/branch
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/branch_type
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/aluout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/pc_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/write_data
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg3
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg4
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg5
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg6
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg7
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg8
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/debug_reg9
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rs
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rt
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rd_sig
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/write_reg_dest
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rd1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rd2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/imm_in
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/imm_ext
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/alu_src_b
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/alu_result
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/branch_taken
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/pc_current
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/pc_next
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/pc_plus4
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/pc_branch
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/lwr_merged_data
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/data_to_mux
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/rf_incr_control
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/read_sel1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/read_sel2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/write_sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/write_ena
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg3_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg4_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg5_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg6_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg7_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg8_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg9_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/write_data
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/data1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/auto_incr
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/data2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/decoded
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/incr_decoded
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/next_val
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/reg_input
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r0
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r3
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r4
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r5
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r6
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r7
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r8
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r9
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r10
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r11
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r12
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r13
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r14
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r15
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r16
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r17
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r18
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r19
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r20
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r21
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r22
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r23
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r24
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r25
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r26
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r27
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r28
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r29
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r30
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/r31
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/DEC/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/DEC/dout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/INC_DEC/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/INC_DEC/dout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG0/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG1/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG2/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG3/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG4/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG5/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG6/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG7/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG8/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG9/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG10/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG11/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG12/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG13/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG14/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG15/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG16/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG17/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG18/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG19/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG20/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG21/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG22/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG23/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG24/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG25/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG26/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG27/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG28/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG29/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG30/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/REG31/q_reg
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din0
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din3
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din4
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din5
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din6
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din7
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din8
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din9
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din10
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din11
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din12
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din13
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din14
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din15
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din16
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din17
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din18
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din19
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din20
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din21
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din22
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din23
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din24
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din25
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din26
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din27
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din28
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din29
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din30
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/din31
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX1/dout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din0
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din3
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din4
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din5
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din6
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din7
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din8
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din9
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din10
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din11
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din12
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din13
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din14
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din15
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din16
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din17
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din18
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din19
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din20
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din21
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din22
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din23
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din24
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din25
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din26
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din27
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din28
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din29
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din30
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/din31
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/RF/MUX2/dout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/SIGN_EXTEND/imm_in
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/SIGN_EXTEND/imm_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALUsrc_Mux/a
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALUsrc_Mux/b
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALUsrc_Mux/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALUsrc_Mux/y
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/data1
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/data2
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/aluop
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/dataout
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/nflag
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/zflag
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/A
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/B
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/ALU_UNIT/result
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/Write_Back_Mux/a
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/Write_Back_Mux/b
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/Write_Back_Mux/sel
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/Write_Back_Mux/y
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/pc_in
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/pc_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/reg_out
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/clk
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/reset
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/load
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/d
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/q
add wave -noupdate /tb_mips_processor/uut/Datapath_Inst/PC_REG/FlopR/q_reg
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/opcode
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/RegDst
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/ALUSrc
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/MemtoReg
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/RegWrite
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/MemRead
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/MemWrite
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/Branch
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/Jump
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/BranchType
add wave -noupdate /tb_mips_processor/uut/Control_Unit_Inst/ALUOp
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/clk
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/memRead
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/memWrite
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/address
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/writeData
add wave -noupdate /tb_mips_processor/uut/Data_Memory_Inst/readData
add wave -noupdate /tb_mips_processor/uut/Instruction_Memory_Inst/a
add wave -noupdate /tb_mips_processor/uut/Instruction_Memory_Inst/rd
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {10894191 ps} {10953682 ps}
